import { FCC, get, set, simpleMergeDeep } from 'onekijs-framework';
import { ColorKeys, ShadowKeys, Theme, ThemeProps } from '../styles/typings';
import { darken, lighten } from '../utils/color';
import React from 'react';
import { ThemeProvider } from 'styled-components';

export const baseTheme = (customTheme: Partial<Theme> = {}): Theme => {
  const theme: Partial<Theme> = {
    breakpoints: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
    },
    colors: {
      white: 'white',
      lightest: 'gray-100',
      light: 'gray-400',
      dark: 'gray-700',
      darkest: 'gray-900',
      black: 'black',
      success: 'green-500',
      info: 'blue-500',
      warning: 'yellow-500',
      danger: 'red-500',
      primary: 'blue-500',
      secondary: 'blue-900',
    },
    palette: {},
    spacings: {
      none: '0',
      '2xs': '0.125rem',
      xs: '0.25rem',
      sm: '0.5rem',
      md: '0.75rem',
      lg: '1rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '2rem',
      '4xl': '2.5rem',
      '5xl': '3rem',
      '6xl': '4rem',
      '7xl': '5rem',
      '8xl': '6rem',
      '9xl': '8rem',
      '10xl': '10rem',
      '11xl': '12rem',
      '12xl': '14rem',
      '13xl': '16rem',
      px: '1px',
    },

    font: {
      families: {
        sans:
          'Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
        serif: 'Georgia, Cambria, "Times New Roman", Times, serif',
        mono: 'Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
      },
      lineHeights: {
        none: 1,
        xs: 1.25,
        sm: 1.375,
        md: 1.5,
        lg: 1.625,
        xl: 2,
        '2xl': 2.5,
        '3xl': 3,
      },
      sizes: {
        '2xs': '.625rem',
        xs: '.75rem',
        sm: '.875rem',
        md: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '4rem',
      },
      spacings: {
        xs: '-0.05em',
        sm: '-0.025em',
        md: 0,
        lg: '0.025em',
        xl: '0.05em',
        '2xl': '0.1em',
      },
      weights: {
        hairline: 100,
        thin: 200,
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
        extrabold: 800,
        black: 900,
      },
    },
    radius: {
      none: 0,
      '2xs': '0.625rem',
      xs: '0.125rem',
      sm: '0.25rem',
      md: '0.375rem',
      lg: '0.5rem',
      xl: '0.625rem',
      full: '9999px',
    },
    shadow: {
      default: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
      xs: '0 0 0 1px rgba(0, 0, 0, 0.05)',
      sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      md: ' 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
      lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
      xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
      '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
      inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
      outline: '0 0 0 3px rgba(66, 153, 225, 0.5)',
      none: 'none',
    },

    sizes: {
      0: 0,
      1: '0.25rem',
      2: '0.5rem',
      3: '0.75rem',
      4: '1rem',
      5: '1.25rem',
      6: '1.5rem',
      8: '2rem',
      10: '2.5rem',
      12: '3rem',
      16: '4rem',
      20: '5rem',
      24: '6rem',
      32: '8rem',
      40: '10rem',
      48: '12rem',
      56: '14rem',
      64: '16rem',
      px: '1px',
      xs: '20rem',
      sm: '24rem',
      md: '28rem',
      lg: '32rem',
      xl: '36rem',
      '2xl': '42rem',
      '3xl': '48rem',
      '4xl': '56rem',
      '5xl': '64rem',
      '6xl': '72rem',
      'screen-sm': '640px',
      'screen-md': '768px',
      'screen-lg': '1024px',
      'screen-xl': '1280px',
    },
    table: {
      bgColor: 'white',
      shadow: ShadowKeys.default,
      thPaddingX: 'md',
      thPaddingY: 'md',
      thBorderBottomWidth: '1px',
      thBorderBottomColor: 'lightest',
      thBgColor: 'light',
      thFontWeigth: 'medium',
      thFontColor: 'dark',
      thFontCase: 'uppercase',
      thFontSize: 'xs',
      thLetterSpacing: 'xl',
      thFilterInputBgColor: 'lightest',
      thFilterInputFontSize: 'sm',
      thFilterInputPaddingX: 'xs',
      thFilterInputPaddingY: 'xs',
      tdFontColor: 'darkest',
      tdPaddingX: 'md',
      tdPaddingY: 'sm',
      tdBorderBottomColor: 'light',
      tdBorderBottomStyle: 'solid',
      tdBorderBottomWidth: '1px',
      tdStripBgColor: 'lightest',
      tdHoverBgColor: 'primary',
      tdHoverFontColor: 'white',
      tdExpandedBgColor: 'lightest',
    },

    input: {
      bgColor: 'white',
      width: 'full',
      borderWidth: 1,
      borderColor: 'light',
      borderRadius: 'md',
      borderStyle: 'solid',
      borderFocusColor: 'primary',
      borderFocusWidth: 2,
      paddingX: 'sm',
      paddingY: 'xs',
      appearance: 'none',
      outline: 'none',
      fontColor: 'darkest',
      placeholderColor: 'light',
    },

    label: {
      fontWeight: 'medium',
      fontCase: 'none',
      fontColor: 'dark',
      fontSize: 'inherit',
      letterSpacing: 'md',
      requiredColor: 'danger',
      requiredWeight: 'bold',
      requiredMarginLeft: 'xs',
      helperIconColor: 'primary',
      helperMarginLeft: 'sm',
    },

    checkbox: {
      color: 'primary',
      bgColor: 'white',
    },
  };
  Object.keys(ColorKeys).forEach((kind) => {
    set(theme, `buttons.${kind}`, {
      bgColor: kind,
      bgColorDisabled: lighten(get(theme.colors, kind, ''), 200),
      bgColorFlat: 'transparent',
      bgColorFlatDisabled: 'transparent',
      bgColorOutline: 'transparent',
      bgColorOutlineDisabled: 'transparent',
      borderColor: kind,
      borderColorDisabled: lighten(get(theme.colors, kind, ''), 200),
      borderColorFlat: 'transparent',
      borderColorFlatDisabled: 'transparent',
      borderColorOutline: kind,
      borderColorOutlineDisabled: lighten(get(theme.colors, kind, ''), 200),
      borderRadius: 'sm',
      borderStyle: 'solid',
      borderWidth: 1,
      color: ['light', 'lightest', 'white'].includes(kind) ? 'darkest' : 'white',
      colorDisabled: ['light', 'lightest', 'white'].includes(kind) ? 'darker' : 'lightest',
      colorFlat: kind,
      colorFlatDisabled: lighten(get(theme.colors, kind, ''), 200),
      colorOutline: ['light', 'lightest', 'white'].includes(kind) ? 'darkest' : kind,
      colorOutlineDisabled: lighten(get(theme.colors, kind, ''), 200),
      cursor: 'pointer',
      cursorDisabled: 'not-allowed',
      fontSize: 'md',
      fontWeight: 'bold',
      hoverColor: ['light', 'lightest', 'white'].includes(kind) ? 'black' : 'white',
      hoverColorDisabled: ['light', 'lightest', 'white'].includes(kind) ? 'darker' : 'lightest',
      hoverColorFlat: lighten(get(theme.colors, kind, ''), 100),
      hoverColorFlatDisabled: lighten(get(theme.colors, kind, ''), 200),
      hoverColorOutline: kind,
      hoverColorOutlineDisabled: lighten(get(theme.colors, kind, ''), 200),
      hoverBgColor: darken(get(theme.colors, kind, ''), 100),
      hoverBgColorDisabled: lighten(get(theme.colors, kind, ''), 200),
      hoverBgColorFlat: 'transparent',
      hoverBgColorFlatDisabled: 'transparent',
      hoverBgColorOutline: lighten(get(theme.colors, kind, ''), 400),
      hoverBgColorOutlineDisabled: 'transparent',
      hoverBorderColor: darken(get(theme.colors, kind, ''), 100),
      hoverBorderColorDisabled: lighten(get(theme.colors, kind, ''), 200),
      hoverBorderColorFlat: 'transparent',
      hoverBorderColorFlatDisabled: 'transparent',
      hoverBorderColorOutline: kind,
      hoverBorderColorOutlineDisabled: lighten(get(theme.colors, kind, ''), 200),
      letterSpacing: 'normal',
      lineHeight: '3xl',
      paddingY: 'none',
      paddingX: 'lg',
      textOverflow: 'ellipsis',
      textTransform: 'none',
      whiteSpace: 'nowrap',
    });
  });

  return simpleMergeDeep(customTheme, theme);
};

export const BaseTheme: FCC<ThemeProps> = ({ theme = baseTheme(), children }) => {
  const GlobalStyles = theme.GlobalStyles;
  return (
    <>
      {GlobalStyles && <GlobalStyles theme={theme} />}
      <ThemeProvider theme={theme}>{children}</ThemeProvider>
    </>
  );
};
